### ISSUE TITLE
Some Autocompletion Errors

### ISSUE THREAD

**Issue by cyril-duss** [Sweeper777/KancolleWikiViewer#1]
while Testing all the functions I notice,d that the Autocompletion suggests, for example, "12.7cm Twin Gun Mount Model B Kai Ni" which would lead you to an wrong page. All the Improved DD Main guns are actually labeled "Kai 2" instead of Kai Ni (more of a wiki inconsistency)

**Comment by Sweeper777** [comment]
Yeah, you are right. I got all the equipment names from https://raw.githubusercontent.com/KC3Kai/kc3-translations/master/data/en/items.json and some of them don't match the wiki name. If you have a better source for equipment names, please do tell me.

**Comment by cyril-duss** [comment]
Getting a good Name List certainly is quite difficult, I went and checked how the wikia equipment list worked (https://kancolle.wikia.com/wiki/Equipment) though that didn't really help as it's source code is just an iterator over all equipment pieces from https://kancolle.wikia.com/wiki/Category:Equipment and I'm not really versed well enough in the way that database works. So I'm not sure if that is extractable in a usable Format.

**Comment by Sweeper777** [comment]
I see that you have created a repsoitory containing all the equipment names. Thank you! It would be really good if that’s in JSON as the extension is in javascript.

**Comment by cyril-duss** [comment]
A little Update:
I found a way to get the whole Equipment category exported as an XML File:
by adding the Category "Equipment" and "Enemy_equipment" on this site:
https://kancolle.wikia.com/wiki/Special:Export
now i put together a json, thogh i'm not sure if it's usable as it turned out a bit weird.
and it might also contain some duplicates or links to categories/partials

**Comment by cyril-duss** [comment]
I have to admit that I'm not really satisfied with this way of handling the names, as its pretty much just thrown together manually and quite whacky, and will need manual updating for each update

**Comment by Sweeper777** [comment]
I just had an amazing idea. What if I use Google's "I'm feeling lucky" feature? Entering things like "kancolle wikia 12.7cm Twin Gun Mount Model B Kai Ni" goes to exactly the desired page. Now I just need to find which url to send a request to.

**Comment by cyril-duss** [comment]
Ok this solution is silly, i like it
it seems like googles Feel lucky isn't callable this way anymore
so i tried the mthod described on this site: https://www.alfredforum.com/topic/5927-force-im-feeling-lucky/
and it's almost perfect... but just almost as you'll land on the module and not on the wiki site...
Which makes this even more Frustrating... so close but still wrong...

**Comment by Sweeper777** [comment]
OMG this silly idea actually works! Now I can keep using the name list I've always been using. And apparently, the feeling lucky links doesn't seem to work on Safari...

**Comment by Sweeper777** [comment]
Fixed in commit [6ffc28e](https://github.com/Sweeper777/KancolleWikiViewer/commit/6ffc28ec90ef5dea1496bfd6b2d6b136e8c12076)
